# Generated by Django 5.1.2 on 2024-10-14 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_grievance_phno_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.area'),
        ),
    ]
